// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"eventsourcing/services/products/api/models"
)

// PatchOKCode is the HTTP code returned for type PatchOK
const PatchOKCode int = 200

/*PatchOK OK

swagger:response patchOK
*/
type PatchOK struct {

	/*
	  In: Body
	*/
	Payload *models.PatchProduct `json:"body,omitempty"`
}

// NewPatchOK creates PatchOK with default headers values
func NewPatchOK() *PatchOK {

	return &PatchOK{}
}

// WithPayload adds the payload to the patch o k response
func (o *PatchOK) WithPayload(payload *models.PatchProduct) *PatchOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch o k response
func (o *PatchOK) SetPayload(payload *models.PatchProduct) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PatchBadRequestCode is the HTTP code returned for type PatchBadRequest
const PatchBadRequestCode int = 400

/*PatchBadRequest BadRequest

swagger:response patchBadRequest
*/
type PatchBadRequest struct {
}

// NewPatchBadRequest creates PatchBadRequest with default headers values
func NewPatchBadRequest() *PatchBadRequest {

	return &PatchBadRequest{}
}

// WriteResponse to the client
func (o *PatchBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PatchInternalServerErrorCode is the HTTP code returned for type PatchInternalServerError
const PatchInternalServerErrorCode int = 500

/*PatchInternalServerError InternalServerError

swagger:response patchInternalServerError
*/
type PatchInternalServerError struct {
}

// NewPatchInternalServerError creates PatchInternalServerError with default headers values
func NewPatchInternalServerError() *PatchInternalServerError {

	return &PatchInternalServerError{}
}

// WriteResponse to the client
func (o *PatchInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
