// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"eventsourcing/services/products/api/models"
)

// ProductsOKCode is the HTTP code returned for type ProductsOK
const ProductsOKCode int = 200

/*ProductsOK OK

swagger:response productsOK
*/
type ProductsOK struct {

	/*
	  In: Body
	*/
	Payload models.ProductList `json:"body,omitempty"`
}

// NewProductsOK creates ProductsOK with default headers values
func NewProductsOK() *ProductsOK {

	return &ProductsOK{}
}

// WithPayload adds the payload to the products o k response
func (o *ProductsOK) WithPayload(payload models.ProductList) *ProductsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the products o k response
func (o *ProductsOK) SetPayload(payload models.ProductList) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ProductsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.ProductList{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ProductsInternalServerErrorCode is the HTTP code returned for type ProductsInternalServerError
const ProductsInternalServerErrorCode int = 500

/*ProductsInternalServerError InternalServerError

swagger:response productsInternalServerError
*/
type ProductsInternalServerError struct {
}

// NewProductsInternalServerError creates ProductsInternalServerError with default headers values
func NewProductsInternalServerError() *ProductsInternalServerError {

	return &ProductsInternalServerError{}
}

// WriteResponse to the client
func (o *ProductsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
