// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"eventsourcing/services/products/api/models"
)

// ProductOKCode is the HTTP code returned for type ProductOK
const ProductOKCode int = 200

/*ProductOK OK

swagger:response productOK
*/
type ProductOK struct {

	/*
	  In: Body
	*/
	Payload *models.Product `json:"body,omitempty"`
}

// NewProductOK creates ProductOK with default headers values
func NewProductOK() *ProductOK {

	return &ProductOK{}
}

// WithPayload adds the payload to the product o k response
func (o *ProductOK) WithPayload(payload *models.Product) *ProductOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the product o k response
func (o *ProductOK) SetPayload(payload *models.Product) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ProductOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ProductNotFoundCode is the HTTP code returned for type ProductNotFound
const ProductNotFoundCode int = 404

/*ProductNotFound NotFound

swagger:response productNotFound
*/
type ProductNotFound struct {
}

// NewProductNotFound creates ProductNotFound with default headers values
func NewProductNotFound() *ProductNotFound {

	return &ProductNotFound{}
}

// WriteResponse to the client
func (o *ProductNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// ProductInternalServerErrorCode is the HTTP code returned for type ProductInternalServerError
const ProductInternalServerErrorCode int = 500

/*ProductInternalServerError InternalServerError

swagger:response productInternalServerError
*/
type ProductInternalServerError struct {
}

// NewProductInternalServerError creates ProductInternalServerError with default headers values
func NewProductInternalServerError() *ProductInternalServerError {

	return &ProductInternalServerError{}
}

// WriteResponse to the client
func (o *ProductInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
