// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Products
//
//  API for handling products.
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /products
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
