// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new products API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for products API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	Add(params *AddParams, opts ...ClientOption) (*AddCreated, error)

	Patch(params *PatchParams, opts ...ClientOption) (*PatchOK, error)

	Product(params *ProductParams, opts ...ClientOption) (*ProductOK, error)

	Products(params *ProductsParams, opts ...ClientOption) (*ProductsOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  Add Add a product.
*/
func (a *Client) Add(params *AddParams, opts ...ClientOption) (*AddCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAddParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Add",
		Method:             "POST",
		PathPattern:        "/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &AddReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*AddCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Add: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  Patch Partially update a product.
*/
func (a *Client) Patch(params *PatchParams, opts ...ClientOption) (*PatchOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPatchParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Patch",
		Method:             "PATCH",
		PathPattern:        "/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PatchReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PatchOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Patch: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  Product Get product by ID.
*/
func (a *Client) Product(params *ProductParams, opts ...ClientOption) (*ProductOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewProductParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Product",
		Method:             "GET",
		PathPattern:        "/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ProductReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ProductOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Product: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  Products Get all products.
*/
func (a *Client) Products(params *ProductsParams, opts ...ClientOption) (*ProductsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewProductsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Products",
		Method:             "GET",
		PathPattern:        "/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ProductsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ProductsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Products: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
