// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewProductsParams creates a new ProductsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewProductsParams() *ProductsParams {
	return &ProductsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewProductsParamsWithTimeout creates a new ProductsParams object
// with the ability to set a timeout on a request.
func NewProductsParamsWithTimeout(timeout time.Duration) *ProductsParams {
	return &ProductsParams{
		timeout: timeout,
	}
}

// NewProductsParamsWithContext creates a new ProductsParams object
// with the ability to set a context for a request.
func NewProductsParamsWithContext(ctx context.Context) *ProductsParams {
	return &ProductsParams{
		Context: ctx,
	}
}

// NewProductsParamsWithHTTPClient creates a new ProductsParams object
// with the ability to set a custom HTTPClient for a request.
func NewProductsParamsWithHTTPClient(client *http.Client) *ProductsParams {
	return &ProductsParams{
		HTTPClient: client,
	}
}

/* ProductsParams contains all the parameters to send to the API endpoint
   for the products operation.

   Typically these are written to a http.Request.
*/
type ProductsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the products params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ProductsParams) WithDefaults() *ProductsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the products params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ProductsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the products params
func (o *ProductsParams) WithTimeout(timeout time.Duration) *ProductsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the products params
func (o *ProductsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the products params
func (o *ProductsParams) WithContext(ctx context.Context) *ProductsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the products params
func (o *ProductsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the products params
func (o *ProductsParams) WithHTTPClient(client *http.Client) *ProductsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the products params
func (o *ProductsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ProductsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
