// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"eventsourcing/internal/api_clients/products/models"
)

// ProductsReader is a Reader for the Products structure.
type ProductsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ProductsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewProductsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewProductsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewProductsOK creates a ProductsOK with default headers values
func NewProductsOK() *ProductsOK {
	return &ProductsOK{}
}

/* ProductsOK describes a response with status code 200, with default header values.

OK
*/
type ProductsOK struct {
	Payload models.ProductList
}

func (o *ProductsOK) Error() string {
	return fmt.Sprintf("[GET /][%d] productsOK  %+v", 200, o.Payload)
}
func (o *ProductsOK) GetPayload() models.ProductList {
	return o.Payload
}

func (o *ProductsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewProductsInternalServerError creates a ProductsInternalServerError with default headers values
func NewProductsInternalServerError() *ProductsInternalServerError {
	return &ProductsInternalServerError{}
}

/* ProductsInternalServerError describes a response with status code 500, with default header values.

InternalServerError
*/
type ProductsInternalServerError struct {
}

func (o *ProductsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /][%d] productsInternalServerError ", 500)
}

func (o *ProductsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
