// Code generated by go-swagger; DO NOT EDIT.

package orders

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewOrderParams creates a new OrderParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewOrderParams() *OrderParams {
	return &OrderParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewOrderParamsWithTimeout creates a new OrderParams object
// with the ability to set a timeout on a request.
func NewOrderParamsWithTimeout(timeout time.Duration) *OrderParams {
	return &OrderParams{
		timeout: timeout,
	}
}

// NewOrderParamsWithContext creates a new OrderParams object
// with the ability to set a context for a request.
func NewOrderParamsWithContext(ctx context.Context) *OrderParams {
	return &OrderParams{
		Context: ctx,
	}
}

// NewOrderParamsWithHTTPClient creates a new OrderParams object
// with the ability to set a custom HTTPClient for a request.
func NewOrderParamsWithHTTPClient(client *http.Client) *OrderParams {
	return &OrderParams{
		HTTPClient: client,
	}
}

/* OrderParams contains all the parameters to send to the API endpoint
   for the order operation.

   Typically these are written to a http.Request.
*/
type OrderParams struct {

	/* ID.

	   Order's ID.

	   Format: uuid
	*/
	ID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the order params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OrderParams) WithDefaults() *OrderParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the order params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OrderParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the order params
func (o *OrderParams) WithTimeout(timeout time.Duration) *OrderParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the order params
func (o *OrderParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the order params
func (o *OrderParams) WithContext(ctx context.Context) *OrderParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the order params
func (o *OrderParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the order params
func (o *OrderParams) WithHTTPClient(client *http.Client) *OrderParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the order params
func (o *OrderParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the order params
func (o *OrderParams) WithID(id strfmt.UUID) *OrderParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the order params
func (o *OrderParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *OrderParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
