// Code generated by go-swagger; DO NOT EDIT.

package orders

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"eventsourcing/services/orders/api/models"
)

// OrderOKCode is the HTTP code returned for type OrderOK
const OrderOKCode int = 200

/*OrderOK OK

swagger:response orderOK
*/
type OrderOK struct {

	/*
	  In: Body
	*/
	Payload *models.Order `json:"body,omitempty"`
}

// NewOrderOK creates OrderOK with default headers values
func NewOrderOK() *OrderOK {

	return &OrderOK{}
}

// WithPayload adds the payload to the order o k response
func (o *OrderOK) WithPayload(payload *models.Order) *OrderOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the order o k response
func (o *OrderOK) SetPayload(payload *models.Order) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *OrderOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// OrderNotFoundCode is the HTTP code returned for type OrderNotFound
const OrderNotFoundCode int = 404

/*OrderNotFound NotFound

swagger:response orderNotFound
*/
type OrderNotFound struct {
}

// NewOrderNotFound creates OrderNotFound with default headers values
func NewOrderNotFound() *OrderNotFound {

	return &OrderNotFound{}
}

// WriteResponse to the client
func (o *OrderNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// OrderInternalServerErrorCode is the HTTP code returned for type OrderInternalServerError
const OrderInternalServerErrorCode int = 500

/*OrderInternalServerError InternalServerError

swagger:response orderInternalServerError
*/
type OrderInternalServerError struct {
}

// NewOrderInternalServerError creates OrderInternalServerError with default headers values
func NewOrderInternalServerError() *OrderInternalServerError {

	return &OrderInternalServerError{}
}

// WriteResponse to the client
func (o *OrderInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
